[package]
name = "rustruut"
version = "0.0.1"
edition = "2021"
license-file = "LICENSE"
description = "This version DOES NOT WORK - publish test"

[lib]
name = "rustruut"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
